In [8]:
import numpy as np
arr2d = np.array([[1,2,3] ,[2,3,4] ,[7,8,9]])
print(arr2d)
sum_of_col = np.sum(arr2d, axis =  0)
print(sum_of_col)


#3d array
arr3d = np.array([[[1,2] ,[3,4] ,[5,6]] , [[1,4] ,[2,6] , [7,9]]])
print(arr3d , arr3d.shape)
print (arr3d[0, 2, 1])

[[1 2 3]
 [2 3 4]
 [7 8 9]]
[10 13 16]
[[[1 2]
  [3 4]
  [5 6]]

 [[1 4]
  [2 6]
  [7 9]]] (2, 3, 2)
6


In [11]:
#vectorization
arr = np.array([1 , 2 , 3 , 4 ,7 ,8])
print(arr**2)
print(arr + 10)
print(arr % 2)

[ 1  4  9 16 49 64]
[11 12 13 14 17 18]
[1 0 1 0 1 0]


In [13]:
#broadcasting
arr1 = np.array([2 ])
arr2 = np.array([3 , 34, 35 , 76 , 43])
print (arr1 + arr2)

[ 5 36 37 78 45]
