In [2]:
#ones array
import numpy as np
arr = np.ones((3,3))
print(arr)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
#full array
arr = np.full((2, 3 ),20)
print(arr)

[[20 20 20]
 [20 20 20]]


In [5]:
#identity matrix 
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
#range function
arr = np.arange(1 , 10)
print(arr)


[1 2 3 4 5 6 7 8 9]


In [13]:
#even no
arr = np.arange(0 , 10 , 2)
print(arr)
#skip every 3rd no
arr1 = np.arange(1 , 14 , 2)
print(arr1)
#linespace
arr3 = np.linspace(1 , 100 , 4)
print(arr3)

[0 2 4 6 8]
[ 1  3  5  7  9 11 13]
[  1.  34.  67. 100.]


In [29]:
#reshaping of array
arr = np.array([[1,2,3] , [4,5,6]])
print(arr , len(arr) , arr.shape)

reshaped = arr.reshape((3 , 2))
print(reshaped , reshaped.shape)
#flattend
flattend = arr.flatten()
print(flattend)


[[1 2 3]
 [4 5 6]] 2 (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6]


In [34]:
#indexing
arr = np.array([1 , 2 , 3 ,4 , 5])
print(arr[2])

#fancy indexing
idx = [0 , 1 , 3]
print(arr[idx])

#boolean indexing 
print(arr[arr>3])

#slicing
print(arr[1:3])
print(arr.dtype)

3
[1 2 4]
[4 5]
[2 3]
int64
